version: "3.8"
 
services: # adds 1 service:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
     - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: admin #(Required) set the password for the root superuser account.
      PMA_HOST: 0.tcp.eu.ngrok.io:10836 # 192.168.180.31 define the address/hostname of the mysql server eg mysql container name.
      PMA_USER: root # this is the root user to login on startup
      PMA_PASSWORD: admin # use the root password to login on startup.
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
 
volumes: # add persistent data even if container is removed.
  my-db:
