# This is a basic workflow to help you get started with Actions

name: Preview Environment

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]


jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: Deploy Preview Environment
      uses: okteto/deploy-preview@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: pr-${{ github.event.number }}-youngestdev
        scope: personal
        timeout: 15m
    
