# This is a basic workflow to help you get started with Actions

name: Delete Preview Environment

# Controls when the workflow will run
on:
  pull_request:
    types:
      - closed
jobs:
  closed:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: Delete Preview Environment
      uses: okteto/destroy-preview@master
      with:
        name: pr-${{ github.event.number }}-youngestdev
        
        
