# This is a basic workflow to help you get started with Actions

name: Deploy Preview Environment

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  preview:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Login
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: Deploy The Preview Environment
      uses: okteto/deploy-preview@master
      env: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: pr-${{ github.event.number }}-namespace
        scope: personal
        timeout: 15m
      
      
      
